### ISSUE TITLE
Reading back sub microsecond times in Python

### ISSUE THREAD

**Issue by erikfrojdh** [slsdetectorgroup/slsDetectorPackage#119]
In our python bindings we rely on the conversion from std::chrono::duration to a Python datetime.timedelta object. Since the precision of Pythons timedelta is 1 microsecond we can't represent sub-microsecond times. 

For setting this can be worked around by passing a float, but for reading back currently you will get 0 for sub-microsecond times. 

```python
>>> d.exptime = 50e-9 #50ns
>>> d.exptime
0.0
```

Potential solutions is to migrate to pandas Timedelta which has nanosecond precision or to use numpy.timedelta64. But pandas would be another dependency and timedelta64 has a less intuitive API.

- https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Timedelta.html
- https://numpy.org/doc/stable/reference/arrays.datetime.html

**Comment by thattil** [comment]
@lrlunin: Will update this issue
