### ISSUE TITLE
New Feature Request for Gotthard2 Receiver

### ISSUE THREAD

**Issue by jiaguozhang** [slsdetectorgroup/slsDetectorPackage#130]
##### Describe the solution you'd like:

Purpose: Perform common mode correction, pedestal correction, noise rejection and gain correction for input frame, and then sum up the number of photons. Finally save limited number of frames (N) into a file.

User input:
	1. Number of frames (N) to be saved
          2. 2 pedestal dataset for 1280 strips (for frame: 0, 2, 4, 6…; as well as 1, 3, 5, 7…)
          3. 2 gain dataset for 1280 strips (for frame: 0, 2, 4, 6…; as well as 1, 3, 5, 7…)
          4. Whether common mode correction (CMC) is activated, if yes which strip channels to be used in common mode calculation
          5. Energy of X-ray photon

Procedure:
	1. First N frames from the receiver will be saved into a chuck of memories
	2. Calculate the common mode for the N frames (if CMC is activated, otherwise skip) 			and perform CMC for the N frames
	3. Perform pedestal correction for frame 0, 2, 4, 6… using 1st pedestal dataset and for 			frame 1, 3, 5, 7 using 2nd pedestal dataset
	4. Perform gain correction for frame 0, 2, 4, 6… using 1st gain dataset and for frame 1, 			3, 5, 7 using 2nd gain dataset, and then divided by energy of X-ray photon
	5. Take the round value as the number of photons for each strip; any values less than 0 		are assigned to 0 (including fake negative values)
	6. The next N frames (frame-N+1… 2N) will be processed with the same procedure 			from 1-5 and add together accordingly to the first N frames
	7. Till all frames are taken and received, only the data from the N frames to be saved 			into a file

Note:
	1. Missing packet will not processed and added to the results
	2. Total number of missing packets for each of the N frames will be saved or written 			somewhere

**Comment by thattil** [comment]
Its decided to use a fast server to write the files and use existing python script to convert to photons. To keep processing separate from the receiver. If this doesn't work, we can discuss again.
