### ISSUE TITLE
New Bug Report

### ISSUE THREAD

**Issue by tintig** [slsdetectorgroup/slsDetectorPackage#132]
##### *Distribution: 

sl6

##### *Detector type: 

eiger

##### *Software Package Version: 

developer tag 2020.08.10_dev0

##### Priority:

medium

##### *Describe the bug

I am not able anymore to choose a specific trimbit file for detector 0: , another one for detector 1:... etc.. it used to be the case before

##### Expected behavior

It ignores the p 0:trimbits and does the same as p trimbits

sls_detector_put 0:trimbits  ~/slsnewrep/developer/slsDetectorPackage/settingsdir/eiger/standard/eigernoise.sn049
- 16:37:27.464 INFO: Settings file loaded: /home/l_msdetect/slsnewrep/developer/slsDetectorPackage/settingsdir/eiger/standard/eigernoise.sn049
- 16:37:27.464 INFO: Settings file loaded: /home/l_msdetect/slsnewrep/developer/slsDetectorPackage/settingsdir/eiger/standard/eigernoise.sn049
- 16:37:27.464 INFO: Settings file loaded: /home/l_msdetect/slsnewrep/developer/slsDetectorPackage/settingsdir/eiger/standard/eigernoise.sn049
- 16:37:27.464 INFO: Settings file loaded: /home/l_msdetect/slsnewrep/developer/slsDetectorPackage/settingsdir/eiger/standard/eigernoise.sn049
trimbits /home/l_msdetect/slsnewrep/developer/slsDetectorPackage/settingsdir/eiger/standard/eigernoise.sn049

**Comment by thattil** [comment]
Fixed and pushed to developer. Made tag 2020.08.12.dev0 so you can test in conda.
