### ISSUE TITLE
Eiger: transmission delay

### ISSUE THREAD

**Issue by tintig** [slsdetectorgroup/slsDetectorPackage#136]
##### *Distribution: 

sl6 (should not matter)

##### *Detector type: 

Eiger
##### *Software Package Version: 

developer (2020.08.12.dev0 )
##### Priority:

medium

##### *Describe the bug

I have checked and I really believe txndelays do not work. I am in 10Gb, which at some point was important as there was a bug happening for 10Gb only on the transmission. 

##### Expected behavior

I believe the delays are set somehow. I see the server printing it when we set them, but are ignored at acquisition time.

##### To Reproduce

For an eiger module, 10Gb, I used very large delays  
sls_detector_put txndelay_frame 1000000000
sls_detector_put 1:txndelay_right 50000000
sls_detector_put 0:txndelay_right 10000000
sls_detector_put 1:txndelay_left 200000000
sls_detector_put txndelay_left 50000

At sls_detector_get status, the server outputs:
Will wait for 1 ms
INFO: Status: IDLE

at acquisition (dr 4 , parallel 1, frames 30000, speed full_speed), the server outputs 
Transmitting...
Will wait for 0 us

and i cannot see with dstat any lowering of the receiver speed at 0 delays or at the large delays.

**Comment by thattil** [comment]
@tintig I can reproduce the issue. It does look like it has no effect. I am reading the registers (different read registers during acquisition) and it all returns 0 and hence, it doesnt wait. I need to wait for @mbrueckner-psi  when he is back from holidays to recheck the registers, in case it has been changed.

**Comment by erikfrojdh** [comment]
@mbrueckner-psi identified this as a firmware bug introduced in version 26. He is working on a fix and we will keep the issue open until the new fw is available.

**Comment by thattil** [comment]
@tintig : @mbrueckner-psi has made a firmware fix.
