### ISSUE TITLE
M3: Trans delay

### ISSUE THREAD

**Issue by kozlowp1** [slsdetectorgroup/slsDetectorPackage#137]
##### *Detector type: 

Mythen3
##### *Software Package Version: 

developer
##### Priority:

Super High 
##### Additional context:

Adding delay for time multiplexing during acquisition from many modules. The register is 0x120 and the value is 24bit long unsigned type. The value means the no. of str. clk. cycles.

**Comment by thattil** [comment]
125 MHz clock, so min value is 8ns and max is 134 ms

**Comment by thattil** [comment]
@kozlowp1 @anberga  Its merged into developer
