### ISSUE TITLE
eigerDetectorServer blocking

### ISSUE THREAD

**Issue by erikfrojdh** [slsdetectorgroup/slsDetectorPackage#142]
##### *Distribution: 
Reproduced on Fedora but presumable all since it's on the server side. 

##### *Detector type: 
Eiger

##### *Software Package Version: 
4.2.0 (potentially others)

##### Priority:
High

##### *Describe the bug
The eigerDetectorServer stops responding resulting in commands sent to it blocks...
The stop server keeps functioning

##### Expected behavior
Not blocking =)

##### To Reproduce
Run concurrent requests, either status or temperature on the stop server while doing an acquire or status start.

##### Additional context
Also reported on the 9M

**Comment by erikfrojdh** [comment]
**Update:** Problem occurs due to a race condition between the control server and the stop server. Commands going to the front end FPGA are accessing the same link. 

**Current advice:**  Avoid running commands that go to the front end FPGA  eg. status and temperature at the same time as starting an acquisition.

**Comment by thattil** [comment]
**Update:** 
This issue exists for all releases.

**Temporary Fix:** 
For now, the temporary fix is to move temp_fpgafl and temp_fpgafr to the control server so that it cannot be accessed while a blocking acquire is in progress.

**Permanent Fix:**
The other issues with accessing via the stop server (such as status, stop) remains but are not urgent as the users have not produced it so far. One can reproduce it using a script asking for status constantly, which our users do not do at the moment.
Therefore, we are working on a permanent fix, which will be included in later releases.

**Comment by xiaoqiangwang** [comment]
Is this issue also applicable to other detectors? I often have one extra thread polling the detector status, while the main thread accepts commands.

**Comment by thattil** [comment]
> Is this issue also applicable to other detectors? I often have one extra thread polling the detector status, while the main thread accepts commands.

No, only Eiger has a local link to communicate with the front end board, which can't be accessed from the control server and stop server at the same time.

**Comment by xiaoqiangwang** [comment]
Ok. In case of Eiger, is it safe to poll detector status, receiver status and detector temperature in a separate thread?

**Comment by thattil** [comment]
Do you use the blocking acquire or the non blocking startReceiver(), startDetector(), stopReceiver() routine?

**Comment by xiaoqiangwang** [comment]
I use the blocking acquire in the main thread.

**Comment by thattil** [comment]
So, this problem exists for all releases in Eiger and the result is that the control server gets stuck and needs to be restarted. So far, we have never heard anyone come back with a problem like this. We found out when we started a script on the detector reading temperature continuously. So, it seems to happen only this way so far.

However, we would advise against getting detector status and temperature from a separate thread for Eiger, while blocking acquire is ongoing.

Moreover, fpga_fl and fpga_fr in the developer branch, now go to the control server (as a temporary fix). Therefore, when you pull these 2 temperatures from a separate thread while a blocking acquire is on going, it will wait until acquire is finished.

Technically, even doing a stop while blocking acquire is going on, could result also in the same problem (as it goes via a stop server to the front end boards), but we have not tried in earnest to reproduce this yet. We will try now and if we do manage, we will have to implement some kind of locking in shared memory to the front end boards as a temporary solution. When we do this, you should be able to do everything (status, temperature included) during blocking acquire. Will get back to you about this.

**Comment by xiaoqiangwang** [comment]
> Technically, even doing a stop while blocking acquire is going on, could result also in the same problem (as it goes via a stop server to the front end boards)
Is this applicable to other detector servers, like MYTHEN3?

**Comment by thattil** [comment]
> > Technically, even doing a stop while blocking acquire is going on, could result also in the same problem (as it goes via a stop server to the front end boards)
> 
> Is this applicable to other detector servers, like MYTHEN3?

No. Only for Eiger. All the other detectors write directly to registers from the control and stop servers. Only eiger uses local links to access the front end board for some commands.

**Comment by thattil** [comment]
@xiaoqiangwang @tintig @mbrueckner-psi 
We have implemented locking in shared memory when accessing the front end boards.
So, it should be fine to access status, stop and temperature from stop server while acquiring or sending commands (including blocking acquire) from the control server.
