### ISSUE TITLE
MY3: slsDetectorGUI crashing often

### ISSUE THREAD

**Issue by anberga** [slsdetectorgroup/slsDetectorPackage#145]
##### *Distribution: 

RHEL7

##### *Detector type: 

Mythen3

##### *Software Package Version: 

developer

##### Priority:

Medium

##### *Describe the bug

The GUI crashes sometimes when not in use.
Very often, after the acquisition (i.e. detector idle) if I zoom on the data, and then move the mouse out of the plot area it crashes. Not sure if it happens also without zooming.

##### Expected behavior

Not crashing?

##### To Reproduce

Acquire an image with mythen3
Zoom on it
Quickly move the mouse out of the plot area (e.g. bottom right)
Segmentation fault

**Comment by thattil** [comment]
https://github.com/slsdetectorgroup/slsDetectorPackage/pull/551
