### ISSUE TITLE
GUI sends commands just by moving the mouse on top of it

### ISSUE THREAD

**Issue by anberga** [slsdetectorgroup/slsDetectorPackage#146]
##### *Distribution: 

RHEL7

##### *Detector type: 

Mythen3

##### *Software Package Version: 

developer
##### Priority:

Low
##### *Describe the bug

When moving the mouse on top of the GUI, commands are sent to the receiver e.g. filename when the mouse pointer exists the file name entry (even without clicking)
##### Expected behavior

Filename is sent only when it is changed
Otherwise we risk to mess up things when the detector is controlled e.g. by GUI and command line in parallel
##### To Reproduce

Move the mouse on top of the filename entry
The seceiver and the GUI print 
INFO: filename set to...

**Comment by thattil** [comment]
Are there others? Or just this field?
I am hovering over the file name field and it doesn't print it. If I click on the field and then outside, it sets it.

**Comment by thattil** [comment]
@anberga I cant reproduce this with RHEL7 either. I hover all over file name field and no command is being sent (also no print out in receiver or gui that it is being set)

**Comment by thattil** [comment]
qlinedit kept editingFinished(), but in the slot, check for isModified() and setModified(false)
qspinbox and qdoubleSpinbox, changed from editingFinished() to valueChanged(), but disabled keyboard tracking in form.

So only for any changes, they will get set. A PR has been made. Will merge by monday.
