### ISSUE TITLE
GUI hangs when aborting an acquisiton

### ISSUE THREAD

**Issue by xiaoqiangwang** [slsdetectorgroup/slsDetectorPackage#148]
##### *Distribution: 
RHEL7

##### *Detector type: 
eigerDetectorServerMaster_virtual

##### *Software Package Version: 
developer

##### Priority:
High

##### *Describe the bug
Start a measurement of 5 seconds exposure, and try to stop before it finishes. The GUI will hang indefinitely.

##### Expected behavior
The GUI will properly stop and recover.

**Comment by thattil** [comment]
This is fixed now. 
Note: In the virtual server, the check for stop flag is only checked at the beginning of every frame, so it will still wait for 5s before returning. If you have 2 frames, it should return in 5s instead of 10s though. Please allow for this delay for the virtual server.
