### ISSUE TITLE
MY3 RDO pll VCO frequency change

### ISSUE THREAD

**Issue by kozlowp1** [slsdetectorgroup/slsDetectorPackage#151]
##### *Detector type: 

Mythen3
##### Priority:

High

##### Additional context:

A change of VCO frequency for rdo pll from 1250Mhz to 1000 Mhz is required. This will affect the final frequency after applying a division factor.

**Comment by thattil** [comment]
![Screenshot from 2020-09-01 09-48-48](https://user-images.githubusercontent.com/33750417/91822805-94faa780-ec38-11ea-9a21-879ccc7ed95b.png)
  
Please let me know if the corresponding clocks and vco frequencies match the new firmware.

**Comment by thattil** [comment]
![Screenshot from 2020-09-01 11-57-31](https://user-images.githubusercontent.com/33750417/91835967-6c7ba900-ec4a-11ea-8098-e91e6805f293.png)
 This is the latest update

**Comment by thattil** [comment]
pushed to developer
