### ISSUE TITLE
trimval tab enable also for MYTHEN3  in the GUI

### ISSUE THREAD

**Issue by anberga** [slsdetectorgroup/slsDetectorPackage#162]
##### *Detector type: 

Mythen3

##### *Software Package Version: 

developer
##### Priority:

Super Low
##### *State the feature:

In the Advanced/Trimming the possibility of setting a trimbit value for all channels should be enabled

Would also be nice to be able to load a trimbit file.

##### Is your feature request related to a problem. Please describe:

The entry to set the trimbit value is disabled.

**Comment by thattil** [comment]
#163 
@anberga  In expert mode, trimming tab and loading trimbits (via Utilities menu) has been enabled for mythen3.
Could you please confirm with a proper trimming file?

**Comment by thattil** [comment]
confirmed
