### ISSUE TITLE
G2: Continuous mode with internal timing

### ISSUE THREAD

**Issue by jiaguozhang** [slsdetectorgroup/slsDetectorPackage#165]
##### *State the feature:

It is possible to set continuous mode using: p burstmode 0. This sets to continuous mode using external timing. It seems that we have to be able to set to continuous mode using internal timing as well.

##### Describe the solution you'd like:

Create a new argument: burstmode 3. This sets through SPI the ASIC configuration address 1100 to proper values for continuous mode using internal timing. 
For address 1100, there are 6 bits (bit-5..., bit-0) can be set. Setting bit-2 to 1 and bit-1 to 0 will set the detector to continuous mode using internal timing.

**Comment by thattil** [comment]
@lopez-c @jiaguozhang 
This is how it will be implemented
0- burst_internal
1- burst_external
2- cw_internal
3- cw_external
