### ISSUE TITLE
M3 Dead-time free mode

### ISSUE THREAD

**Issue by kozlowp1** [slsdetectorgroup/slsDetectorPackage#169]
##### *Detector type: 

MIII
##### Priority:

Medium
##### *State the feature:

Allowing for turning on the dead time-free mode that allows for parallelizing the execution of exposure, readout and streaming of data. The min. exp. time is 18.8us for run & rdo clk = 125Mhz (division factor 8). 

##### Describe the solution you'd like:

A command for enable dead-time free mode : enabling 0 bit at the address 0x580
For checking out errors look at the 4th bit of the same address. If 1 then the exposure was too short.

##### Additional context:

Please find the register description below:
Description of the dead-time free controller: section 12 : https://www.overleaf.com/read/tmsbgfwznqpj

@anberga

**Comment by thattil** [comment]
@anberga

**Comment by thattil** [comment]
The feature command will be "parallel" to be set to 0 or 1. Default will be 0. 
When requesting detector status and end of acquisition, the mentioned register and bit will also be checked and "ERROR" returned for status if the bit is set to 1.

**Comment by thattil** [comment]
Most likely merged tomorrow

**Comment by thattil** [comment]
@kozlowp1 @anberga 
If you want to test before it is merged (maybe tomorrow), use the m3parallel branch
