### ISSUE TITLE
M3 SW trigger and start readout

### ISSUE THREAD

**Issue by kozlowp1** [slsdetectorgroup/slsDetectorPackage#172]
##### *Detector type: 

MIII
##### Priority:

Medium
##### Describe the solution you'd like:

I added two toggle bits in the control register 0x84. 

One of them stands for readout only execution. It starts only readout FSM without exposure
start readout:
p setbit 0x84 3

A new frame can be triggered by a software trigger now. It works in the same way like the external 
trigger, but the pulse comes from the CPU instruction.
sw trigger:
p setbit 0x84 4

The changes are added to the chapter 7 of the documentation:
https://www.overleaf.com/project/5e78c85beda6510001df420f

**Comment by thattil** [comment]
@kozlowp1 @anberga 
Pawel, Anna asked me to implement only sw trigger for now. start readout is a test phase at the moment. When its ready to be put into the software, we can reopen this issue or create a new one for it. For now, only sw trigger will be implemented.

**Comment by kozlowp1** [comment]
Hey, could you revert the issue? Anna asked me about the start readout bit today, could you implement a command for that?

**Comment by thattil** [comment]
#209 should implement a non blocking readout. It upto you to set number of frames etc in receiver to not show missing packets. Since its non blocking, it will not show in gui.
Expects frame number increasing and status to transmittig connected when reading out.
