### ISSUE TITLE
MY3: default clock dividers and pattern clock

### ISSUE THREAD

**Issue by anberga** [slsdetectorgroup/slsDetectorPackage#174]
##### *Detector type: 

Mythen3
##### *Software Package Version: 

developer
##### Priority:

Medium
##### *State the change request:

Change default clock dividers:
clkdiv 0 10 # readout clock
clkdiv 1 10 # smp sample clk (x2)
clkdiv 2 5 # run clk
clkdiv 3 10 # sync clk (not used)

In function startPattern:
- Read run clock divider
- set run clock to slower frequency (clkdiv 2 20)
- Start pattern
- Wait 10ms (?)
- Set back to initial value

##### Is your change request related to a problem. Please describe:

Too fast clock with dividers 8,4
Divider faster than 20 in the pattern prevents trimming

**Comment by thattil** [comment]
@kozlowp1

**Comment by anberga** [comment]
From measurments, it seems that things work fine with 
clkdiv 2 20
and all the other 
clk xx 10

**Comment by anberga** [comment]
From measurments, it seems that things work fine with 
clkdiv 2 20
and all the other 
clk xx 10

**Comment by anberga** [comment]
From measurments, it seems that things work fine with 
clkdiv 2 20
and all the other 
clk xx 10

**Comment by thattil** [comment]
@kozlowp1 @anberga 
![Screenshot from 2020-09-08 17-29-16](https://user-images.githubusercontent.com/33750417/92496801-e8509500-f1f8-11ea-9bd0-e153c534c810.png)

This will be the new clocks.

**Comment by thattil** [comment]
@anberga: @kozlowp1  has requested me to keep smp_clk (timing rxr: one going to the triggers) the same as before and not be changed, which is clkdiv 5 and 200 MHz. Also according to you, I will not change run clock before and after executing startPattern().
Here is the final list of clocks
![Screenshot from 2020-09-09 15-55-53](https://user-images.githubusercontent.com/33750417/92608102-3925c380-f2b5-11ea-8e4c-b4535c6752a2.png)
