### ISSUE TITLE
[G2 server] - Number of frames in CW mode

### ISSUE THREAD

**Issue by lopez-c** [slsdetectorgroup/slsDetectorPackage#185]
##### *Detector type: 

Gotthard2
##### *Software Package Version: 

developer
##### Priority:

Low
##### *State the feature:

The number of frames to acquire in continuous mode is stored in register 0x298-0X29c. In CW mode only, the number of frames must be stored in register 0x118-0x11C. Therefore, when the operation mode is changed from burst to CW mode, the value of this register must also be updated.

**Comment by thattil** [comment]
when switching to burst mode, this register is left as is.  
It is set
- when setting continuous mode
- swithcing from burst mode to continuous mode 
merged to developer now #186
