### ISSUE TITLE
MY3: set exptime to 0 for disabled counters

### ISSUE THREAD

**Issue by anberga** [slsdetectorgroup/slsDetectorPackage#197]
##### *Detector type: 

Mythen3

##### *Software Package Version: 

developer

##### Priority:

Medium

##### *State the feature:

When changing exptime, the exposure time is set to that value for the counters which are enabled, 0 for the the ones which are disabled. Eventually keep the value in memory to set it in case the counters are re-enabled.

When counters are disabled, the exposure time is set to 0 for the disabled counters; when counters are enabled they are set the value stored in memory.

##### Is your feature request related to a problem. Please describe:

No enabling counter which are anyways not read out reduces the noise. People normally use exptime (and not exptime1,2,3) so they risk not to take it into account.

##### Describe the solution you'd like:

The enables signals to the disabled counetrs are not toggled by the FW.

##### Describe alternatives you've considered:

Use exptime1,2,3 separately but it's very error prone.

**Comment by thattil** [comment]
@anberga @kozlowp1 
also writing 0 to gate delay registers if counters are not enabled.
