### ISSUE TITLE
MY3: default clock and pipeline; clock when trimming

### ISSUE THREAD

**Issue by anberga** [slsdetectorgroup/slsDetectorPackage#198]
##### *Detector type: 

Mythen3 

##### *Software Package Version: 

developer
##### Priority:

Medium
##### *State the change request:

Use as default values:
clkdiv 0 10 # readout clock
clkdiv 1 10 # smp sample clk (x2)
# sys pll
#clkdiv 2 5 # run clk
clkdiv 2 10 # run clk
clkdiv 3 10 # sync clk (not used)
#pipeline: register 0x110, bit6-4: pipeline, bit1-0: additional offset
reg 0x110 0x80

When trimming (setTrimbits function)
clkdiv 2 40 # run clk
and put it back to previous value at the end of the function

##### Is your change request related to a problem. Please describe:

Correct pipeline for readout
Slower clock required when trimming

**Comment by thattil** [comment]
@kozlowp1 @anberga 
run clk updated to 10 div, when trimming at 40 clkdiv
pipeline reg (as per @kozlowp1 ): has 4 bits, defaults sets to 0x80.
