### ISSUE TITLE
MIII Trigger rerouting

### ISSUE THREAD

**Issue by kozlowp1** [slsdetectorgroup/slsDetectorPackage#202]
##### *Detector type: 

Mythen3
##### Priority:

High
##### *State the feature:

Changing the way we use the flow FSM for the auto-mode. Now all the nodes will work in the "old" external triggering mode by default:
1. Set bit 0 in the 0x4C0 reg to 1 by default (after startup) and forget about it
The triggers are controlled only by master node. To provide external or SW trigger  enable triggers in the new defined bit in the config register:
2. p setbit 0x80 8
To makes things clear, the flow FSM is used a bit differently than in GII, we first arm all the nodes and then provide a trigger - if in auto-mode the trigger is provided immediately from the Master. 

##### Describe the solution you'd like:

1. Set bit 0 in the 0x4C0 reg to 1 by default 
2. p setbit 0x80 8 (trigger enable should go there now instead of 0x4C0)
The rest stays the same.
##### Additional context:

We need to deterministically synchronise all the nodes with flat cable.

**Comment by thattil** [comment]
0x4c0 bit 0 will be the flow trigger bit in software that is always set for m3 only at server start up.

The trigger enable bit that was in 0x4c0 0 bit to 0x80 (control reg) bit 8.
