### ISSUE TITLE
MY3: trimbit_scan sends more frames than expected 

### ISSUE THREAD

**Issue by anberga** [slsdetectorgroup/slsDetectorPackage#206]
##### *Detector type: 

Mythen3
##### *Software Package Version: 

developer
##### Priority:

High
##### *Describe the bug

Does not happen always

When acquiring a trimbit scan we get more than the expected 64 images (see picture). 

![20201018_124602](https://user-images.githubusercontent.com/34126852/96566857-627b3b80-12c6-11eb-8260-746da21f7904.jpg)
The servers prints the right number of steps etc.
We tried to confirm conters and dynamic range several time, but could not fix it.
When scanning the trimbits offline (i.e for i in $(seq 0 1 63); do sls_detector_put trimval; sls_detector_acquire; done)
it works with no issues.

##### Expected behavior

When I counfigure the trimbit scan between 0 and 63 step 1 I expect 64 images back

could you also change the syntax to
sls_detector_put scan trimbits 0 63 1 (instead of sls_detector_put scan trimbit_scan... )

##### To Reproduce

sls_detector_put scan trimbit_scan 0 63 1
sls_detector_acquire
But it doesn't happen always...

##### Screenshots

![20201018_124602](https://user-images.githubusercontent.com/34126852/96566857-627b3b80-12c6-11eb-8260-746da21f7904.jpg)

**Comment by thattil** [comment]
Changed "trimbit_scan" to "trimbits".
Will add usleep between resetting pll or according to what firmware requires.
