### ISSUE TITLE
Overload setPattern

### ISSUE THREAD

**Issue by anberga** [slsdetectorgroup/slsDetectorPackage#217]
##### *Detector type: 

Mythen3, CTB, Moench
##### *Software Package Version: 

developer
##### Priority:

Low
##### *State the feature:

loading Pattern works only from file, not from memory

##### Is your feature request related to a problem. Please describe:

If I generate the pattern in python, I would like to load it without having to write it to file

##### Describe the solution you'd like:

overload setPattern function such that it can accept also the array ow words/addresses, instead of the filename

##### Describe alternatives you've considered:

Write to file and read it back or load word by word

**Comment by thattil** [comment]
@anberga 
Since you are loading this from python, I will just make a Detector API expecting a struct patternParameters and Position. The patternparameters is what we use when loading from file to send to the detector server. So we will reuse ti.
