### ISSUE TITLE
[My3] Finishing patternstart, startreadout and clkdiv commands after FW finishes its operation.

### ISSUE THREAD

**Issue by kozlowp1** [slsdetectorgroup/slsDetectorPackage#224]
##### *Detector type: 

Mythen3
##### Priority:

Medium
##### *State the feature:

In order to avoid overlap of the execution of the following commands:
patternstart 
startreadout 
clkdiv 
clkphase

##### Is your feature request related to a problem. Please describe:

It would be nice to block execution of a next command until the current one finishes.
Neither readout nor pattern should not start to run before PLL is synchronised.
Bacause of resource sharing of the pattern and readout signals one should not run them in parallel.

##### Describe the solution you'd like:

Therefore an elegant way is to just block finishing of the above commands until they really finish their job on
the firmware :) 

##### Describe alternatives you've considered:

There is no synchronisation between all those cases in FW and that's not a good idea to do 
this there. 

##### Additional context:

The following busy bits are to be used (0 -means not busy, 1 - means busy):

0x200 (pattern_flow_ctrl) 
STATUS_R 0x00
rsm_busy : 0 bit
csm_busy : 17 bit 

0x000 (ctrl) 
A_SYSTEM_STATUS_R 0x06
rpll_locked_r: 1 bit (run clock -> clk 2)
rdo_plllocked_r: 2 bit (readout clock -> clk 0, clk 1)

0x500 (asic_rdo) 
REG_STATUS 0x0
busy_r : 1 bit

**Comment by anberga** [comment]
Also for clkphase (same signal as clkdiv)

**Comment by kozlowp1** [comment]
I see a veery long plllocked signal. I discussed with Carlos, there is a procedure for changing the frequency, you have this probably somewhere in your software. Actually it is you who is resetting the PLL, therefore the locked signal is somehow controlled by software. That means that one doesn't necessairly need to poll for finishing the locked signal because it is software that controls the period of it.

**Comment by thattil** [comment]
@kozlowp1 Can you confirm A_SYSTEM_STATUS_R is 0x05 for Gotthard2? This is important for me as they share same code for PLL.

**Comment by thattil** [comment]
@kozlowp1 @lopez-c 
I have connected the pll locked bits to check for status after resetting pll (wait for it to go high). They are not checked for Gotthard2, only for Mythen3.
