### ISSUE TITLE
Receiver reports 0 caught frames for Eiger partial readout

### ISSUE THREAD

**Issue by erikfrojdh** [slsdetectorgroup/slsDetectorPackage#236]
When operated in partial readout (e.g. readnlines 128) the receiver reports 0 caught frames even though there is no "real" packet loss.

**Comment by thattil** [comment]
This feature is only a temporary implementation to ignore the "red missing packets", but the slsReceiver writes the full image padding the "missing packets", which are not really missing. To properly implement this feature, this goes into ROI feature, that is put off until 'complete image assembler' is incorporated. For now, this will be pushed off until properly implemented in the future.
