### ISSUE TITLE
Copydetectorserver returns success even if the BFIN  disk is full

### ISSUE THREAD

**Issue by almoxx** [slsdetectorgroup/slsDetectorPackage#238]
##### *Detector type: 
JF
##### *Software Package Version: 
5.0.2
##### Priority:
Med
##### *Describe the bug
Copydetectorserver returns success even if the BFIN  disk is full
##### Expected behavior
Copydetectorserver returns error/optional ask to delete older versions.
##### To Reproduce
(sf-daq) [dbe@sf-daq-2 ~]$ sls_detector_put 6-copydetectorserver jungfrauDetectorServerv5.0.2 sf-daq-2
- 17:09:45.295 INFO: Sending detector server jungfrauDetectorServerv5.0.2 from host sf-daq-2
- 17:09:45.295 INFO: Sending detector server jungfrauDetectorServerv5.0.2 from host sf-daq-2
- 17:09:45.295 INFO: Sending detector server jungfrauDetectorServerv5.0.2 from host sf-daq-2
- 17:09:45.295 INFO: Sending detector server jungfrauDetectorServerv5.0.2 from host sf-daq-2
- 17:09:45.295 INFO: Sending detector server jungfrauDetectorServerv5.0.2 from host sf-daq-2
- 17:09:45.295 INFO: Sending detector server jungfrauDetectorServerv5.0.2 from host sf-daq-2
- 17:09:45.295 INFO: Sending detector server jungfrauDetectorServerv5.0.2 from host sf-daq-2
- 17:09:45.295 INFO: Sending detector server jungfrauDetectorServerv5.0.2 from host sf-daq-2
- 17:09:49.639 INFO: Controller rebooted successfully!
- 17:09:49.640 INFO: Controller rebooted successfully!
- 17:09:49.640 INFO: Controller rebooted successfully!
- 17:09:49.640 INFO: Controller rebooted successfully!
- 17:09:49.640 INFO: Controller rebooted successfully!
- 17:09:49.640 INFO: Controller rebooted successfully!
- 17:09:49.640 INFO: Controller rebooted successfully!
- 17:09:49.640 INFO: Controller rebooted successfully!
copydetectorserver successful
(
(sf-daq) [dbe@sf-daq-2 ~]$ telnet jf16ma-00
Trying 129.129.242.115...
Connected to jf16ma-00.
Escape character is '^]'.

BusyBox v1.16.2 (2012-03-09 11:39:48 CET) hush - the humble shell
Enter 'help' for a list of built-in commands.

root:/> ps
  PID USER       VSZ STAT COMMAND
    1 root       560 S    /sbin/init
    2 root         0 SW   [kthreadd]
    3 root         0 SW   [ksoftirqd/0]
    4 root         0 SW   [kworker/0:0]
    5 root         0 SW<  [kworker/0:0H]
    6 root         0 SW   [kworker/u2:0]
    7 root         0 SW<  [khelper]
    8 root         0 SW<  [writeback]
    9 root         0 SW<  [bioset]
   10 root         0 SW<  [kblockd]
   11 root         0 SW<  [bfin-spi.0]
   12 root         0 SW   [kworker/u2:1]
   13 root         0 SW<  [rpciod]
   14 root         0 RW   [kworker/0:1]
   15 root         0 SW   [kswapd0]
   16 root         0 SW   [fsnotify_mark]
   17 root         0 SW<  [nfsiod]
   18 root         0 SW<  [deferwq]
   19 root         0 SWN  [jffs2_gcd_mtd2]
   31 root       476 S    inetd
   33 root       676 S    -/bin/sh
   34 root       476 S    /sbin/inetd
   35 root       508 S    /sbin/dhcpcd -h jf16ma-00
   36 root      1268 S    /./jungfrauDetectorServerv5.0.0
   38 root      1264 S    /./jungfrauDetectorServerv5.0.0 --stopserver --port
   55 root       500 S    /bin/telnetd
   56 root       680 S    -sh
   57 root       668 R    ps
root:/> 

##### Additional context
happened at SwissFEL on 24.3.21

**Comment by thattil** [comment]
![Screenshot from 2021-06-08 17-39-44](https://user-images.githubusercontent.com/33750417/121215775-97052d00-c880-11eb-9641-b615432dd164.png)

Cant replicate. It seems to show error as expected. Please elaborate how to replicate.

**Comment by thattil** [comment]
circumstances when it was produces has too many unknowns to determine how to reproduce. Matter ignored for now and will be reopened if reproduced in future.
