### ISSUE TITLE
G2: Receiver hangs on long measurments

### ISSUE THREAD

**Issue by jiaguozhang** [slsdetectorgroup/slsDetectorPackage#239]
##### *Distribution: 

RHEL7

##### *Detector type: 

Gotthard2

##### *Software Package Version: 

5.0.1

##### Priority:

High

##### *Describe the bug

Software control: pc8830
Receiver running: pc-jungfrau-test
Data storage: pcmoench01
Frames per trigger: 2720
Triggers: 10 or 20

The data acquisition (sls_detector_acquire) is done in a loop with 18000 times (18000 x sls_detector_acquire each receiving 10 or 20 triggers). After executing the data acquisition for more than 8 hours, the receiver hangs and does not respond any longer. Then one needs to restart the receiver again by interrupting the measurements. 

Once it happens, it is found that the data from the last 1-2 acquisitions were not saved into the disk completely. Something related to data saving? 

##### Expected behavior

Receiver without hanging and responds till the end of the long measurements.

##### To Reproduce

Set-up G2 and control it from pc8830.
Run receiver from pc-jungfrau-test.
Save data into pcmoench01 (data server).

**Comment by erikfrojdh** [comment]
Did you make any progress on this? Once could for example try without saving the data and see if it still happens. 
Also when it hangs could you let me have a look, before restarting?

**Comment by thattil** [comment]
@jiaguozhang Need to run measurement without gui and tuned pc and see if there are still packet loses when writing to disk. If there are, we need to find a solution for g2 recever file writing (buffer before writing etc.).

**Comment by jiaguozhang** [comment]
Carlos tried running the detector directly with a local network. The problem did not occur. It is most likely related to the network from the control pc to the receiver pc. 

Issue closed!
