### ISSUE TITLE
findex overflow at 16bits?

### ISSUE THREAD

**Issue by jiaguozhang** [slsdetectorgroup/slsDetectorPackage#240]
##### *Distribution: 

RHEL7

##### *Detector type: 

Whatever

##### *Software Package Version: 

5.0.1 or whatever

##### Priority:

Medium

##### *Describe the bug

findex counter overflow if taking 74,000 measurements
file index generated from 0,1,2... 65535, 0, 1, 2
seems that index is generated from 16 bit counter

##### Expected behavior

file index generated from 0,1,2... 73999 using 32 bit or 64 bit instead of 16 bit

##### To Reproduce

just taking more than 66000 acquisitions

**Comment by erikfrojdh** [comment]
Hi Jiaguo, 

I can't reproduce you bug. The File index is internally represented using an 64bit integer. Trying to provoke the overflow I get the following. 

./sls_detector_put findex 65535
./sls_detector_acquire
./sls_detector_acquire
./sls_detector_acquire

ls | grep master
run_master_65535.raw
run_master_65536.raw
run_master_65537.raw


or:
[l_msdetect@mpc2726 bin]$ ./sls_detector_put findex 6546549684332214                                                                                                                                                                                           
findex 6546549684332214
[l_msdetect@mpc2726 bin]$ ./sls_detector_get findex
findex 6546549684332214


Could you send me an email with the exact configuration and point me to the machine where it happens? 

Cheers

Erik

**Comment by erikfrojdh** [comment]
Resolved, the issue was a problem with the input script. 
Note: file index can take values up to max(int64): 9223372036854775807
