### ISSUE TITLE
CMake cannot find libzmq

### ISSUE THREAD

**Issue by sdebionne** [slsdetectorgroup/slsDetectorPackage#241]
##### *Distribution: 

Conda

##### *Software Package Version: 

5.1.0

##### Priority:

Low

##### *Describe the bug

Using Conda and zeromq from `conda-forge`:

```
# Name                    Version                   Build  Channel
zeromq                    4.3.4                h9c3ff4c_0    conda-forge
```

zmq is not properly detected.

The reason is that the CMake package defines `ZeroMQ_INCLUDE_DIR` and `ZeroMQ_LIBRARY` while SLS's `CMakeFile.txt` expect `ZeroMQ_INCLUDE_DIRS` and `ZeroMQ_LIBRARIES` (plural which is actually better practice).

I am referring to:

```
target_include_directories(slsSupportObject 
  PUBLIC
    "$<BUILD_INTERFACE:${CMAKE_CURRENT_SOURCE_DIR}/include>"
    "$<INSTALL_INTERFACE:${CMAKE_INSTALL_INCLUDEDIR}>"
  PRIVATE
    ${ZeroMQ_INCLUDE_DIR}
)

target_link_libraries(slsSupportObject 
  PUBLIC
    slsProjectOptions 
    ${ZeroMQ_LIBRARY}
    rapidjson
  PRIVATE
    slsProjectWarnings     
)
``` 

IMHO, a solution would be to use imported targets, so that the details of the variable names would be hidden:

```
target_link_libraries(slsSupportObject 
  PUBLIC
    slsProjectOptions 
    ZeroMQ::ZeroMQ
    rapidjson
  PRIVATE
    slsProjectWarnings     
)
```

but that require to fix the upstream libzmq project that has a poor CMake integration...

**Comment by erikfrojdh** [comment]
Do you still have this issue? I think we link the libzmq target and don't use the  ${ZeroMQ_INCLUDE_DIR} anymore. If you still have issues (with 6.x) please let us know and we will get on it.
