### ISSUE TITLE
Eiger: Blocking software trigger 

### ISSUE THREAD

**Issue by erikfrojdh** [slsdetectorgroup/slsDetectorPackage#243]
##### *Detector type: 
Eiger but preferably more detectors for consistency.  

##### *Software Package Version: 
developer 

##### Priority:
 Medium

##### *State the feature:
An acquire like version of the trigger command. **"blocking_trigger"** or **"btrigger"**?

##### Is your feature request related to a problem. Please describe:
This feature would help with scans on the uXAS and MS beamline, reducing the overhead for each frame.

##### Describe the solution you'd like:
blocking_trigger would work in a similar way as acquire (only maybe not waiting for the receiver) keeping the socket open until the detector status is waiting again.

**Comment by erikfrojdh** [comment]
Martin has prepared the Eiger firmware for this feature

slightly rephrased:
> the new/modified firmwarecan be found at
> /afs/psi.ch/project/pilatusXFS/Firmware/bitfiles/v29
> It only contains feb files since beb hasn't been modified.
> 
>  I've modified the feb top_level_status register which is read only
> register #3 (counting from 0) and overall register number #23
> 
> in that register it is bit #5 (from 0) which contains the signal itself
> and #6 contains the toggle bit.
> 
> bit #5 => 0x20
> bit #6 => 0x40

**Comment by thattil** [comment]
16..31 -> temperature
Check toggle as in acquisition before reading exposure (confirm with Martin about toggle)

**Comment by thattil** [comment]
new bit mask:
bit #5 => 0x20 (exposure)
bit #6 => 0x40 (exposure_falling edge toggle)
bit #7 => 0x80 (exposure_rising edge toggle)

**Comment by thattil** [comment]
5th bit-> wait for trigger bit
checks if detector is waiting for trigger, else throw
no checks to ensure detector latched trigger, but is guaranteed that software triggers are latched
