### ISSUE TITLE
G2 25 um detector virtual hdf file with image reconstruction

### ISSUE THREAD

**Issue by jiaguozhang** [slsdetectorgroup/slsDetectorPackage#272]
##### *Detector type: 

Gotthard2

##### *Software Package Version: 

early 2022

##### Priority:

Low

##### *State the feature:

Virtual hdf file with reconstructed images from two modules of a G2 25 um pitch detector.

##### Additional context:

@jiaguozhang

**Comment by thattil** [comment]
Unable to use hyperslab with negative stride for the slave module. Pursuing alternate options, including firmware upgrade.

**Comment by thattil** [comment]
Since firmware will reverse the slave module channels, we can hyperslab without issues :)
