### ISSUE TITLE
Jungfrau detector does not start after being stopped

### ISSUE THREAD

**Issue by lopez-c** [slsdetectorgroup/slsDetectorPackage#336]
##### *Detector type: 
Jungfrau

##### *Software Package Version: 
6.0.1

##### Priority:
Medium

##### *State the change request:
The modification introduced in commit # 016d0d7face36f5dab3bcbd135c0db70017aff7e needs to modified. 

##### Is your change request related to a problem. Please describe:
Under some circumstances the detector cannot be started once it has been stopped. We believe that there should be a delay between the stop pulse and the resetCore function call, to give enough time to readout and stream out the ongoing frame. 

##### Additional context:
The issue is not always reproduceable, several retries may be needed to get it reproduced. The issue can be reproduced in trigger and auto mode.  Summary of settings used to reproduce the issue:
exptime 0.000470
readoutspeed full_speed
period 0.000500
numinterfaces 2
timing trigger

**Comment by thattil** [comment]
6.1.1 released
