### ISSUE TITLE
M3: vthreshold doesnt work

### ISSUE THREAD

**Issue by thattil** [slsdetectorgroup/slsDetectorPackage#364]
##### *Detector type: 

M3
##### *Software Package Version: 

developer
##### Priority:

High
##### *Describe the bug

vthrehsold doesnt work

##### Additional context

@anberga

**Comment by anberga** [comment]
when I try
put dac vthreshold 1000
The server crashes "Segmentation fault"

If I have 3 counters enabled, it sets vth2, vth3 and crashes before setting vth1;
If I only have counter 0 enabled, the server doesn't print anything - not even that it's trying to set vth1. It just crashes.

get dac vthreshold 
works properly
