### ISSUE TITLE
M3 Functions

### ISSUE THREAD

**Issue by erikfrojdh** [slsdetectorgroup/slsDetectorPackage#365]
Add polarity, interpolation and pump probe to M3:
CSR_invpol = 4
CSR_interp = 6
CSR_pumprobe = 8

#CHIP STARTUS REGISTER BITS
CSR_spypads = 0
CSR_invpol = 4
CSR_dpulse = 5
CSR_interp = 6
CSR_C10pre = 7 #default
CSR_pumprobe = 8
CSR_apulse = 9
CSR_C15sh = 10
CSR_C30sh = 11 #default
CSR_C50sh = 12
CSR_C225ACsh = 13 # Connects 225fF SHAPER AC cap (1: 225 to shaper, 225 to GND. 0: 450 to shaper)
CSR_C15pre = 14

vicin dac -> 800
@anberga

**Comment by anberga** [comment]
put as default gain values
C30sh | C10pre
I think they currently are
C30sh | C15pre

**Comment by thattil** [comment]
For after beamtime
