### ISSUE TITLE
MÖNCH: python API returns 0 for all exptimes less than 1e-6 seconds (Duplicate #119)

### ISSUE THREAD

**Issue by lrlunin** [slsdetectorgroup/slsDetectorPackage#402]
##### *Describe the bug

Using the python API and a Moench class attribute `exptime` all possible exposures can be set properly. This can be checked with the opened `slsDetectorGUI` instance. So, there is no bug in C++ API. However it's not possible to read them in python API out. Beginning from the 1e-6 exposures and lower python API returns `0.0`.   

##### Distribution: 

RHEL 7.9

##### Software Package Version: 

tag 2022.2.3.dev0

##### Priority:

high

##### Expected behavior

It seems like you need to switch the type of return variable in python api

##### Screenshots

![image](https://user-images.githubusercontent.com/1849145/156387570-a1698fa9-9550-4b46-86a1-5165208d238a.png)
![image](https://user-images.githubusercontent.com/1849145/156387655-6b2254dd-d6ea-4589-ab75-b0c8578807b1.png)
![image](https://user-images.githubusercontent.com/1849145/156387966-c38e0e01-0982-4bfb-a5ce-36dff77e8a85.png)

**Comment by lrlunin** [comment]
The same problem occurs with delay for the 7th digit after point.

**Comment by thattil** [comment]
This was already an issue earlier #119. It had low priority as we hardly set time less than 1us. We are looking into a solution and might replace numpy.timedelta.

**Comment by thattil** [comment]
Will be updating the original issue #119. Please check that for further updates.
