### ISSUE TITLE
MÖNCH: wrong frame chunks arrangement

### ISSUE THREAD

**Issue by lrlunin** [slsdetectorgroup/slsDetectorPackage#403]
##### *Describe the bug
It seems like in the last update the order of packets or its indexes were broken. The picture is therefore wrong "assembled" in the zmq process, in .tiff and in .raw data as well.

##### Distribution: 

RHEL 7.9

##### Detector type or Receiver: 

Moench

##### Software Package Version: 

dev build from 2022.02.03

##### Priority:

SUPER HIGH

##### Expected behavior

corrupted image in the newest software version:
![image](https://user-images.githubusercontent.com/1849145/156652930-306474a6-154c-4985-b61d-3aa3faded526.png)
the same image in the software from dev build 2021.05.10
![image](https://user-images.githubusercontent.com/1849145/156653061-a33e61f1-030e-4407-b46c-d0cb84182ffa.png)

**Comment by thattil** [comment]
@anberga @lrlunin
Seems to be resolved already and not a bug.
