### ISSUE TITLE
Eiger: nextframenumber && modules out of sync

### ISSUE THREAD

**Issue by lhdamiani** [slsdetectorgroup/slsDetectorPackage#404]
##### *Describe the bug
The nextframenumber parameter do not gets updated after an acquisition (it keeps the previously stored valued) and is ignored once a new acquisition starts.

```
[dbe@xbl-daq-28 xbl-daq-28]$ sls_detector_put nextframenumber 1
nextframenumber 1
[dbe@xbl-daq-28 xbl-daq-28]$ sls_detector_put start && sls_detector_put stop
start successful
stop successful
```

From the DAQ synchronizer, I know that 32 frames were sent in this start&&stop:
```
Mar 11 14:39:30 xbl-daq-28.psi.ch bash[10619]: [2022-03-11 13:39:30.896888842] [ZmqPulseSyncReceiver::get_next_pulse_id] Modules in sync ( 32).
```

Therefore, I would expect that the nextframenumber to be 33. But the 'nextframenumber' is still the previously defined value:

```
[dbe@xbl-daq-28 xbl-daq-28]$ sls_detector_get nextframenumber
nextframenumber 1
```

After another start&&stop acquisition:

```
[dbe@xbl-daq-28 xbl-daq-28]$ sls_detector_put start && sls_detector_put stop
start successful
stop successful
```
I received another 29 frames:

```
I Mar 11 14:42:30 xbl-daq-28.psi.ch bash[10619]: [2022-03-11 13:42:30.692637678] [ZmqPulseSyncReceiver::get_next_pulse_id] Modules in sync ( pulse_id 61).
```

This means that it continued from 32 onwards (even though the nextframenumber still is the value stored earlier 1). After two started&stopped acquisitions, the nextframenumber is still the previously defined value that was used at the beginning:

```
[dbe@xbl-daq-28 xbl-daq-28]$ sls_detector_get nextframenumber
nextframenumber 1
```

##### Distribution: 
NAME="Red Hat Enterprise Linux Server"
VERSION="7.9 (Maipo)"
ID="rhel"
ID_LIKE="fedora"
VARIANT="Server"
VARIANT_ID="server"
VERSION_ID="7.9"
PRETTY_NAME="Red Hat Enterprise Linux Server 7.9 (Maipo)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:7.9:GA:server"
HOME_URL="https://www.redhat.com/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"

REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 7"
REDHAT_BUGZILLA_PRODUCT_VERSION=7.9
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="7.9"

##### Detector type or Receiver: 
Eiger (installed at cSAXS)

##### Software Package Version: 
slsdet                    6.1.0            py38hf484d3e_0    slsdetectorgroup
slsdetlib                 6.1.0                hf484d3e_0    slsdetectorgroup

##### Priority:
Not sure what you think about this.

##### Expected behavior
I expect the nextframenumber to be consistent with the actual number of the next frame that will be sent out and that i'm able to get nextframenumber from each module (in order to detect when they are not in sync).

##### Additional context
Additionally, as described in https://slsdetectorgroup.github.io/devdoc/pydetector.html?highlight=nextframenumber#slsdet.Detector.nextframenumber, I'd like to be able to easily detect if the stopped acquisition resulted in different frame numbers for different modules.  This is very important to be able to detect when the modules are out of sync and requires a 'put nextframenumber 1', because if this is the case, the acquisition request cannot be performed and the user must receive a warning/error.

**Comment by thattil** [comment]
I am trying to reproduce this on my end with the same firmware (29) and release (6.1.0). Is this happening every time you do a start and stop?

**Comment by lhdamiani** [comment]
Yes, this happens after every start/stop. The receiver node is xbl-daq-28, do you have access to it?
