### ISSUE TITLE
Receiver writes too many files at high frame rates

### ISSUE THREAD

**Issue by vhinger182** [slsdetectorgroup/slsDetectorPackage#473]
##### *Describe the bug

If the receiver gets too many frames (at high rates) such that it cannot write them, it writes a large number of files with only very few images in each file.

##### Distribution: 

not applicable

##### Detector type or Receiver: 

Receiver used with Jungfrau

##### Software Package Version: 

6.1.1

##### Priority:

Medium

##### Expected behavior

Error message about too high frame rate and switch off of file writing or only write preset max number of files (e.g. only write max 10 files)

##### Additional context

Aldo can provide more context. He has observed the issue a number of times.

**Comment by thattil** [comment]
I believe this has already been resolved (https://github.com/slsdetectorgroup/slsDetectorPackage/issues/417) and pushed to developer. Please have a look at the developer branch
