### ISSUE TITLE
[Jungfrau][rr_rxr]: Cannot reset number of UDP destinations to 1

### ISSUE THREAD

**Issue by alejandrohomsp** [slsdetectorgroup/slsDetectorPackage#488]
##### *Describe the bug
When using the Jungfrau detector with RR receiver patch *[rr_rxr]*, the `udp_clrdst` command does not reset the effective number of UDP destinations kept by the FPGA. Indeed, the `setNumberofDestinations` function in the detector server, changing the corresponding register, is only called by the `F_SET_DEST_UDP_LIST` command, which is issued by the client for UDP entries other than the default one (0). This makes impossible to switch back from multiple RR receivers to the default configuration without resetting the FPGA or the detector.

##### Detector type or Receiver: 
Jungfrau

##### Software Package Version: 
6.1.1

##### Priority:
High

##### Expected behavior
The `udp_clrdst` command should reset the detector to the default non-RR configuration

**Comment by thattil** [comment]
This fix should set the number of destinations in the fpga to 1 and also clear the udp destinations in the fpga.

**Comment by thattil** [comment]
Will be merging developer to rr_rxr now.

**Comment by alejandrohomsp** [comment]
Thanks a lot @thattil for the job! I will test it and let you know as soon as I have some results.

**Comment by thattil** [comment]
Alright, ill reopen this PR if you have any issues.

**Comment by alejandrohomsp** [comment]
Hi @thattil!

I tried to merge the resulting `rr_rxr` branch into our `esrf-round-robin` code, but the amount of changes is rather big. Indeed, [the differences from the previous commit](https://github.com/slsdetectorgroup/slsDetectorPackage/compare/5508f01...afd84b5) affect several subsystems, including the `slsReceiver`. 

In the contest of the `ID29 Jungfrau-4M` integration, it would be better for us to keep the SDK `rr_rxr` as stable as possible. Do we need to integrate all the features merged from `develop`? If not, could you please just apply your changes in 862b72b & 1a5b9ac on top of 5508f01 and generate the embedded `jungfrauDetectorServer` binaries for us?

Thanks a lot in advance!

**Comment by thattil** [comment]
Hi @alejandrohomsp 

Ive done as you have requested. Brought back the commit to 5508f0135d4acfbb2f66c8af5d44f11c9300cd96 and added on top b6db0978001c6bf0959bc5812eaac2ef1ad0a7fe. Please let me know if it works so I can close this issue.

**Comment by alejandrohomsp** [comment]
Hi @thattil

Thanks a lot for the fix. I will test it and let you know if it is OK

**Comment by alejandrohomsp** [comment]
Hi again,

I confirm that the patch works as expected in the `rr_rxr` branch. The command `udp_cleardst` is enough to pass from RR to single-receiver configuration, and we no longer need to perform `resetfpga` at the end of our Lima2 RR application.

I am closing this issue. Thanks a lot!
