### ISSUE TITLE
Building calibration tools

### ISSUE THREAD

**Issue by tpoliaw** [slsdetectorgroup/slsDetectorPackage#5]
I am trying to build this package to calibrate a Mythen detector (at DLS I11) and am having trouble building the calibration tools.

I'm following the guidelines in http://slsdetectors.web.psi.ch/docs/pdf/slsDetectorInstall.pdf. Is this still current?

I have downloaded and built the Root application from https://root.cern/ and that seems to work ok (as far as I can tell). I have set ROOTSYS variables and added it to PATH and LD_LIBRARY_PATH variables .

Running `./cmk.sh` from within an up to date clone of this repo (4.0.1 tag or developer branch) completes successfully and creates executables in the build/bin directory but does not include `energyCalibrationWizard` or `angularCalibrationWizard` mentioned in the pdf above. Are these tools still in use/maintained?

The source for these appears to still be present but my knowledge of the C++/GCC/make/cmake toolchain isn't good enough to start tracing why they're not being built. There is a reference to them in the Makefile but the associated `make calWiz` task fails with `cd: /path/to/slsDetectorPackage/calibrationWizards: No such file or directory`.

Any help would be appreciated and apologies if I've misread or misinterpreted how these tools are intended to be used.

Thanks

**Comment by erikfrojdh** [comment]
Hi Peter, 

Could you contact Anna Bergamaschi ([anna.bergamaschi@psi.ch](url) ) @anberga directly? (probably email is the best) To verify which software you should use for your Mythen installation and specific instructions on the upgrade.

Cheers. 

Erik
