### ISSUE TITLE
Loading .pat with pattern commands ==> All patword to 0x0

### ISSUE THREAD

**Issue by JulianHeymes** [slsdetectorgroup/slsDetectorPackage#527]
CTB - MÖNCH04: Loading pattern files (.pat) with "pattern" instead of "parameters" results in all patword set to 0x0

**Comment by thattil** [comment]
Ctb and moench firmware fixed. version updated on software.
- additionally printout for getting patterm removed to increase speed. user expected to know ctb and moench reading pattern words will execute them as well.
