### ISSUE TITLE
M3 Clock Mapping Update

### ISSUE THREAD

**Issue by kozlowp1** [slsdetectorgroup/slsDetectorPackage#528]
##### State the change request:

The new mapping of clocks could be:

 
The new mapping of clocks:
index   clk              freq              clkdiv                                comment
    0 rdo_clk           83.3 Mhz       12             
    1 rdo_smp_clk  83.3 Mhz       12            
    2 run_clk           50 Mhz          20           
    3 str_clk            125Mhz          8                                  (permanent - do not allow to change it)
    4 smp_clk         200 Mhz         5                                  (permanent - do not allow to change it)

I assigned the maximum reliable readout frequencies.

The current one (if I am not wrong):
 
 
clkdiv 0 10 # readout clock
clkdiv 1 10# readout out clk
clkdiv 2 10# run clk
clkdiv 3 10 # sync clk (not used)
clkdiv 4 10 # str clk (not used)
clkdiv 5 5 # smp clk

##### Detector type: 
Mythen3

##### Priority:
Medium

##### Additional context:
A need to cleanup the number of clocks and the initial attributes.

**Comment by anberga** [comment]
Please keep it in a separate branch!

**Comment by kozlowp1** [comment]
Please also change the APIDATE and COMPDATE both to 220824, so that we know we have a new version of both FW and SW.

**Comment by thattil** [comment]
> Please also change the APIDATE and COMPDATE both to 220824, so that we know we have a new version of both FW and SW.

@kozlowp1 I can only change the required firmware version in software. The change in the API version register is done only in the firmware.
