### ISSUE TITLE
[Moench 3.1] Wrong data alginment during visualisation

### ISSUE THREAD

**Issue by kozlowp1** [slsdetectorgroup/slsDetectorPackage#670]
##### *Distribution: 
RHEL7

##### *Detector type: 
Moench 3.1

##### *Software Package Version: 
moench remove storage cells

##### Priority:
High

##### *Describe the bug
The data in the packet is not plotted properly. There is most likely misalignment of some bytes. 
Instead of pixel value b'0011111111111111 I see b'1111111100111111. I checked with wireshark and the data sent from readout board seems to be correct. It would be nice to make sure our interface is correct.

##### Expected behavior

I test ADC pattern b'0011111111111111  and such value should be visualised in top and bottom part of the "module".

##### To Reproduce
The best is if we can discuss and debug it together. I don't exclude FW problem.

**Comment by thattil** [comment]
incorrect packet numbers in firmware
