### ISSUE TITLE
New functionnality: processing methods for getting images with intensities

### ISSUE THREAD

**Issue by soleil-ica** [slsdetectorgroup/slsDetectorPackage#78]
It could be usefull to have access to post-processing methods in the Sls sdk for building a Jungfrau image with intensities (without the gain information).
for example :

`bool load_gains_map_file_in_memory(const char * bin_path, char * gains_map_buffer, size_t gains_map_buffer_size)` :   To load the bin file which contains the gain coefficients for each pixel.

bin_path : complete path to the bin file.
gains_map_buffer : a buffer allocated by the caller to receive the gains map informations
gains_map_buffer_size : size of the buffer allocated by the caller
return false if an error occured

`bool build_pedestal_image(int gain_index, char * pedestal_image_buffer, size_t pedestal_image_buffer_size) (sync method ?)` : To build the pedestal images for one gain : DYNAMICGAIN, FORCESWICHG1 or FORCESWITCHG2.
It will run an acquisition and will build the pedestal images (averaging all several images).

gain_index : gain index
pedestal_image_buffer : a buffer allocated by the caller to receive the pedestal image (a buffer of 16 bits integers).
pedestal_image_buffer_size : size of the buffer allocated by the caller
return false if an error occured

`build_intensities_image(const char * raw_image, const char * gains_map_buffer, const std::vector<const char *> & pedestal_image_buffers, char * intensities_image)` : To build an image with the intensities.
    
raw_image : buffer of 16 bits integers (adu + gain index)
gains_map_buffer : a buffer with gains map informations
pedestal_image_buffers : a vector of pedestal image buffers (16 bits by pixel)
intensities_image : buffer allocated by the caller to receive the final image. 24 bits for each pixel.

**Comment by erikfrojdh** [comment]
Our sincere apologies for not getting back to you on this issue. It is not foreseen to add any post processing functions directly in the slsDetectorPackage. We rather want to do this on the zmq stream in order to be flexible. 

It might be that we publish some code on the conversion but then maybe in another repo.
