### ISSUE TITLE
Moench: Acquire blocking function with callback

### ISSUE THREAD

**Issue by anberga** [slsdetectorgroup/slsDetectorPackage#795]
##### *Detector type: 

Will be mainly used for moench
##### Priority:

Low
##### *State the feature:

Implement a new sls_detector_acquire (sls_detector_acquire_acquire_zmq ?) with an empty data callback, such that it waits until all data have been processed for moench. 
##### Is your feature request related to a problem. Please describe:

acquire returns before the data have been processed and all the time sequence messes up.
##### Describe the solution you'd like:

Wait until the Zmq process returns

**Comment by thattil** [comment]
@erikfrojdh : Erik's suggestion: http request or something similar waited if set up to wait for in shared memory.
