### ISSUE TITLE
sls_detector_put accepts network TCP/UDP ports above 65535 (16bit)

### ISSUE THREAD

**Issue by mbrueckner-psi** [slsdetectorgroup/slsDetectorPackage#799]
sls_detector_put accepts tcp or udp ports above 65535. The result is a port where the msb's are discarded.
So port 77787 (0x12FDB) => becomes port 12251 (0x2FDB).

##### Expected behavior
An error message while setting ports like 77787 for rx_tcpport, udp_dstport, rx_zmqport, and so on.

##### To Reproduce
sls_detector_put rx_tcpport 77787

##### Additional context
After looking a bit in the code it seems like port numbers are either stored and passed on as int or uint32_t which is both wrong. It should be uint16_t and a check should be done if 0 ≤ port ≤ USHRT_MAX (see limits.h)

**Comment by erikfrojdh** [comment]
Yes, this is a check that we should have. The quick fix is to add a check when setting the port number, and then when we break API we should make the 32->16 bit change. 


Even though it doesn't make a huge difference we should use std::numeric_limits for c++ code. Just looks cleaner =)
```cpp
std::numeric_limits<uint16_t>::max()
std::numeric_limits<uint16_t>::min()
```
