### ISSUE TITLE
Moench 0.3.2 CR - Min. Exptime 100ns

### ISSUE THREAD

**Issue by kozlowp1** [slsdetectorgroup/slsDetectorPackage#840]
##### *Detector type: 
Moench

##### *Software Package Version: 
developer

##### Priority:
Medium

##### *State the change request:
1. Prevent user from setting up exptime lower than 100ns
2. Set firmware version to 231026

**Comment by thattil** [comment]
@kozlowp1 Then shall I remove the minimum acquisition clock for exptime? Previously, we always reduce the clock by 2 before saving it to firmware register. If it becomes negative, we set it to 0. So it looks like the minimum clock was 2. Shall I remove this?

**Comment by thattil** [comment]
@kozlowp1 Waiting on you to test and let me know the new values.

**Comment by thattil** [comment]
It was confirmed that the firmware was sending out incorrect frame number, which the reciever software could not cope with. That is why wireshark showed the packets, but not the slsReceiver. At the moment, it was discussed to merge without any minimum value as exptime 0ns is not vital.
