### ISSUE TITLE
Publish zmq stream on *

### ISSUE THREAD

**Issue by erikfrojdh** [slsdetectorgroup/slsDetectorPackage#902]
When sending data on zmq allow connections on any interface 

Expected behaviour: allow to put * to publish on all interfaces without requiring a specific IP. 

```bash
sls_detector_put rx_zmqip *
```

or replace the start with 0, all or something similar

**Comment by felix-engelmann** [comment]
In general, ZMQ accepts a variety of strings as specifiers to listen on, Some examples are:
- `*`
- `0.0.0.0`
- `2001:db8::42`
- `fe80::cb05:42fe:5423:cc64%wlp0s1` 

For IPv6 addresses, the socket needs to be enabled with
`socket.setsockopt( ZMQ_IPV6, True );`
And the address needs to be wrapped in `[]`, e.g. 
`socket.connect("tcp://[fe80::cb05:42fe:5423:cc64%wlp0s1]:3000")`
