### ISSUE TITLE
Receiver need permission to create folder when setting fpath

### ISSUE THREAD

**Issue by erikfrojdh** [slsdetectorgroup/slsDetectorPackage#905]
When setting fpath using the zmq stream the receiver tries to create the folder even if fwrite is disabled. This leads to issues when wanting to pass on a path for a writer that consumes the zmq stream.

**Comment by felix-engelmann** [comment]
Currently it works by commenting out 
https://github.com/slsdetectorgroup/slsDetectorPackage/blob/97f0c1fe4650bb48cdc2d9ca4d81957af6c674ab/slsReceiverSoftware/src/Implementation.cpp#L530

A solution suggested by @thattil was to add a option to the fpath client command in the likes of (--no-create-directory)

**Comment by thattil** [comment]
A solution by @erikfrojdh is to create the folder only if 'fwrite' is enabled and at the start of acquisition when we create a file before starting the actual acquisition in the detector.
