### ISSUE TITLE
M3: clock divider update

### ISSUE THREAD

**Issue by kozlowp1** [slsdetectorgroup/slsDetectorPackage#914]
Probably for new release, please find the new firmware below:
/afs/psi.ch/project/sls_det_firmware/stripDetector_readout_board_firmware/mythen_III/HW1_2/FWv1_4_1/240402@36cd831c

The firmware version has changed to: 230124

Additionally the rdoclk (index 0) should have clkdiv set to 20 by default (instead of 10) - it should run with 50 Mhz by default instead of 100Mhz. Please update it in the software otherwise users are running into troubles when using lower grade boards.

##### *Detector type: 
Mythen3

##### *Software Package Version: 
8.0.2

##### Priority:
Medium

**Comment by thattil** [comment]
Firmware version already at 0x230124 since jan 2023. Awaiting further info from @kozlowp1 regarding this date.

**Comment by thattil** [comment]
@anberga @kozlowp1 This is on hold at the moment as it is not clear if this is needed and if the firmware version needs an update.

**Comment by thattil** [comment]
@anberga After discussing with @kozlowp1, the firmware version stays the same. The default start up clock divider of clk 0 of readout pll  also stays the same in firmware. Instead, it should be changed in software towards the end of detector setup to 50 MHz.
