### ISSUE TITLE
Blocking acquire stop (Gotthard2 25um)

### ISSUE THREAD

**Issue by erikfrojdh** [slsdetectorgroup/slsDetectorPackage#915]
Stopping an acquire fails with "**Acquisition not successful. Unexpected detector status"**

v8.0.1

**Comment by erikfrojdh** [comment]
Issue is not present in v7 since the check was added to catch waiting modules in v8

**Comment by thattil** [comment]
@erikfrojdh Is this done? Or shall I start to work on this?
