### ISSUE TITLE
Gotthard2 - Reconfigure chip after power cycle

### ISSUE THREAD

**Issue by lopez-c** [slsdetectorgroup/slsDetectorPackage#916]
##### *Detector type: 
Gotthard2

##### *Software Package Version: 
8.0.1

##### Priority:
Medium

##### *State the feature:
Gotthard2 chips get configured only once when the server starts. CHips should also be configured every time the chips are powered on (powerchip). 

##### Describe the solution you'd like:
Similar to other detectors (Jungfrau 1.1), a new configuration should be loaded on the Gotthard2 detector chips when the chips are powered on.

##### Describe alternatives you've considered:
Restarting the server would also do. But then the measurement settings (exposure time, period, frames,...) should be set again.

**Comment by thattil** [comment]
@lopez-c In Jungfrau configuring chip meant just rewriting what is in that register back to it. Is it the same in G2? Rewriting what is in ASIC_CONFIG reg (0x0 + 0x0100)? Or do we  just need to set the config done_bit in the  same register?

**Comment by thattil** [comment]
@lopez-c Should this fix go into 8.0.2? or developer?

**Comment by lopez-c** [comment]
@thattil I would not do a bug-fix, we can add it to the developer branch and release it with the next SW. 
Regarding the change, we need to reload all the onchip parameters: Onchip dacs, ADC configuration, veto reference. Basiucally everything that is loaded to the ASIC when we power ON the detector.

I do not have the full scope of the code and all the implications, but basically everything that ends up calling the function ASIC_Driver_Set() after doing powerChip(1); in setupDetector().

**Comment by thattil** [comment]
> @lopez-c alright, makes sense. Then I will add it in the developer for the next release (minor or major).
