### ISSUE TITLE
Fix: python version and versions cmd with no detector

### ISSUE THREAD

**Issue by erikfrojdh** [slsdetectorgroup/slsDetectorPackage#989]
Add version info in the python package

`slsdet.__version__`

and maybe make versions work even without detector just reporting no detector connected?

**Comment by thattil** [comment]
Anything that cannot be retrieved (from shm or detector or receiver) is just set as "Unknown"

**Comment by erikfrojdh** [comment]
I think we should revisit how to to slsdet.__version__...

**Comment by thattil** [comment]
> I think we should revisit how to to slsdet.**version**...
Sure. We can make a new PR to fix this.
